# Generated by Django 5.2.15 on 2026-06-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20)),
                ('room_id', models.CharField(max_length=20)),
                ('exam_date', models.DateField()),
                ('exam_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
