# Generated by Django 5.2.15 on 2026-07-02 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_scheduler', '0002_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Course code must be like CS101 or CSE201', regex='^[A-Z]{2,4}[0-9]{3}$')]),
        ),
    ]
