# Generated by Django 5.2.15 on 2026-07-02 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_scheduler', '0003_alter_course_course_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Room ID must be like A101', regex='^[A-Z][0-9]{3}$')])),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
