# Generated by Django 5.2.15 on 2026-07-03 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_scheduler', '0005_faculty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
